apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: route53-secrets
  namespace: cert-manager
spec:
  encryptedData:
    route53-key: AgA46jHCdpit6wnwHj7lsCALArvhj6IuN9g/NNaGHah5ldDFZhvUciVPMrtszHhu+0A4HX5oQJtj9YPDiAP0/sGdZndWNvPC8QbRrbFDN/1+AzRxEVNpanctGfjCQV6GPztI3UMOru3LGap26QfGtUML0WWsDtUFGGfulA2ttGLX1mvul190Z4uKfBrWd3yPMz+x9ktj+niQbbaMJudicTjYEdODPkBIbabHYcJyzwo+mqShLBxQHvLvcAHjVs4xLQAw4d/bFDOUMJUFnoGbitXA38b/uTmjlUvUeVVjCpAuaiGaWUdRu4QW4NSsLHhPeDTBJ7uDcXwCaqH+WRGSOtL/tc9csEy1ryBoQKekxfVEFjahp8sj3z5umnNdUNwPXlkJeiWsz6WKvh49rePX/DJMHjHm/LrxTqexxPSjdEwysuY/1OilWCBOkdoOBtaxUI7XcPljjcgsuchppe2TY0AjW+1B6C5UfEph24WmLfN17wlfGTNth16iBK+dV6Z9VDpUooTBeAEMbhHfWOM1+SnTTiCFVuF0maLfYZmMpc4pMnxrF11P8aXcHm26gHtWOD6xFMkAQcY5l2UPXAKnhvkkjLYqjqvvbxz8JN6iTd5egjPrSqk/sn6D2x3vsyfgGuKCGEFls6RRkjOppu+j2sT8y/v5DCB2EbkYek5ypmfQXBhpaaYFdc9AK73S+SwMIWzPwn5lEabBlybDl7tNHJ+9Hrk5GwjZWX+cgJXTpNqsHgal/w176euS
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: route53-secrets
      namespace: cert-manager

