{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::058718939924:role/eksctl-jmtmonster-cluster-ServiceRole-NXWYIP8LJYII
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
